---
title: "R Notebook"
output: html_notebook
---

# Setup

```{r}
library(tidyverse)

# Data directory
dir_data <- "../data"
# Find all the data files
df_files_all <-
  tibble(file = list.files(dir_data, full.names = TRUE)) %>%
  mutate(name = str_sub(str_remove(file, "../data/"), 1, -5))

df_files_all %>% head
```

## Wrangle data

Load the most recent datafile only.

```{r load_raw}
df_data_raw <- 
  df_files_all %>% 
  ## Target data files only
  filter(
    str_detect(file, "csv"),
    str_detect(file, "Vis\\+Perception"), # Valid datasets from Qualtrics Survey
  ) %>% 
  ## Parse date of download from filename
  mutate(
    name = str_remove(name, "Vis+Perception_"),
    name = str_replace_all(name, "[[:punct:]|[:symbol:]]+", " "),
    name = str_match(name, "\\w+ \\d+ \\d+"),
    date = lubridate::mdy(name)
  ) %>% 
  ## Take the latest
  filter(date == max(date)) %>% 
  ## Load the data
  pull(file) %>% 
  read_csv() %>% 
  slice(-1) %>% 
  slice(-1)

df_data_raw
```

Process the raw data.

```{r}
df_data <- 
  df_raw %>% 
  select(
    contains("COM") | 
    contains("NON") | 
    contains("LEN") |
    contains("ANG") |
    contains("AREA") |
    contains("SAT"),
    -UserLanguage
  ) %>% 
  rowid_to_column() %>% 
  pivot_longer(
    cols = -rowid,
    names_sep = "-",
    names_to = c("task", "true"),
    values_to = "response"
  ) %>% 
  mutate(
    x = as.numeric(response),
    x_true = as.numeric(true),
    d = x - x_true,
    d_rel = d / x_true
  )

df_data
```


# Analyze

## Mean error

```{r}
df_data %>% 
  group_by(task) %>% 
  summarize(
    error_mean = mean(abs(d)),
    relerror_mean = mean(abs(d_rel))
  ) %>% 
  arrange(error_mean)
  # arrange(relerror_mean)
```

## Visualize all data (Relative error)

```{r}
df_data %>% 
  # mutate(task = fct_reorder(task, abs(d_rel))) %>% 
  mutate(
    task = fct_relevel(task, "COM", "NON", "LEN", "ANG", "AREA", "SAT")
  ) %>% 
  
  ggplot(aes(task, d)) +
  geom_hline(yintercept = 0, size = 1, color = "grey80") +
  geom_boxplot() +
  rzdr::theme_common() +
  labs(
    x = "Rung",
    y = "Error (Signed)"
  )
```

## Visualize all data (Relative error)

```{r}
df_data %>% 
  # mutate(task = fct_reorder(task, abs(d_rel))) %>% 
  mutate(
    task = fct_relevel(task, "COM", "NON", "LEN", "ANG", "AREA", "SAT")
  ) %>% 
  
  ggplot(aes(task, d_rel)) +
  geom_hline(yintercept = 0, size = 1, color = "grey80") +
  geom_boxplot() +
  rzdr::theme_common() +
  labs(
    x = "Rung",
    y = "Relative Error (Signed)"
  )
```

